Style/FrozenStringLiteralComment:
  Enabled: false

Lint/RedundantRequireStatement:
  Enabled: false

Layout/ArgumentAlignment:
  EnforcedStyle: with_fixed_indentation

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Style/BracesAroundHashParameters:
  EnforcedStyle: no_braces

Style/PercentLiteralDelimiters:
  Enabled: false

Style/SpecialGlobalVars:
  EnforcedStyle: use_english_names

Security/Eval:
  Enabled: false

Style/WordArray:
  EnforcedStyle: brackets

Style/ClassAndModuleChildren:
  Enabled: false

Style/TrivialAccessors:
  Enabled: false

Style/Alias:
  Enabled: false

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Metrics/ClassLength:
  Enabled: false

Naming/MethodParameterName:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Layout/RescueEnsureAlignment:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ModuleLength:
  Enabled: false

Style/ZeroLengthPredicate:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/BlockLength:
  Enabled: false

Metrics/BlockNesting:
  Enabled: false

Style/NumericPredicate:
  Enabled: false

Naming/AccessorMethodName:
  Enabled: false

Naming/MemoizedInstanceVariableName:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/Documentation:
  Enabled: false

Naming/ConstantName:
  Enabled: false

Style/MutableConstant:
  Enabled: false

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/ParameterAlignment:
  EnforcedStyle: with_fixed_indentation

Lint/UnusedMethodArgument:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/RedundantBegin:
  Enabled: false
