
version: '2' 
services:
  mysql:
    image: percona:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=search_cop
    ports:
      - 3306:3306
  postgres:
    image: styriadigital/postgres_hstore:10
    environment:
      POSTGRES_DB: search_cop
      POSTGRES_USER: search_cop
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
